# Generated by Django 6.1 on 2026-08-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, help_text='Address or area details.', max_length=300)),
                ('rental_price', models.DecimalField(decimal_places=2, help_text='Rental price in the base currency.', max_digits=12)),
                ('apartment_type', models.CharField(choices=[('SELF_CONTAINED', 'Self-contained'), ('ONE_BEDROOM', 'One-bedroom'), ('TWO_BEDROOM', 'Two-bedroom'), ('THREE_BEDROOM', 'Three-bedroom'), ('FLAT', 'Flat'), ('DUPLEX', 'Duplex')], max_length=20)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('parking', models.BooleanField(default=False, help_text='Parking is available.')),
                ('electricity', models.BooleanField(default=False, help_text='Electricity supply is available.')),
                ('water', models.BooleanField(default=False, help_text='Water supply is available.')),
                ('security', models.BooleanField(default=False, help_text='Security is available.')),
                ('furnished', models.BooleanField(default=False, help_text='The apartment is furnished.')),
                ('additional_facilities', models.CharField(blank=True, help_text='Any additional facilities not covered by the standard flags.', max_length=500)),
                ('availability', models.BooleanField(default=True, help_text='Whether the apartment is currently available for rent.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('landlord', models.ForeignKey(limit_choices_to={'role': 'LANDLORD'}, on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['location'], name='apartments__locatio_53cb8f_idx'), models.Index(fields=['rental_price'], name='apartments__rental__cdc6f4_idx'), models.Index(fields=['apartment_type'], name='apartments__apartme_133e3e_idx'), models.Index(fields=['landlord'], name='apartments__landlor_6bf206_idx'), models.Index(fields=['availability'], name='apartments__availab_684e5b_idx')],
            },
        ),
    ]
