# Generated by Django 6.1 on 2026-09-11 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartmentimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='video',
            field=models.FileField(blank=True, help_text='Short tour video (MP4, WebM or MOV, up to 50 MB).', null=True, upload_to='apartments/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
    ]
