# Generated by Django 6.1 on 2026-08-30 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Preferred location.', max_length=200)),
                ('max_rent', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum rental price the tenant is willing to pay.', max_digits=12, null=True)),
                ('apartment_type', models.CharField(blank=True, choices=[('SELF_CONTAINED', 'Self-contained'), ('ONE_BEDROOM', 'One-bedroom'), ('TWO_BEDROOM', 'Two-bedroom'), ('THREE_BEDROOM', 'Three-bedroom'), ('FLAT', 'Flat'), ('DUPLEX', 'Duplex')], help_text='Preferred apartment type.', max_length=20, null=True)),
                ('bedrooms', models.PositiveIntegerField(blank=True, help_text='Preferred number of bedrooms.', null=True)),
                ('bathrooms', models.PositiveIntegerField(blank=True, help_text='Preferred number of bathrooms.', null=True)),
                ('parking', models.BooleanField(blank=True, help_text='Parking is required.', null=True)),
                ('electricity', models.BooleanField(blank=True, help_text='Electricity supply is required.', null=True)),
                ('water', models.BooleanField(blank=True, help_text='Water supply is required.', null=True)),
                ('security', models.BooleanField(blank=True, help_text='Security is required.', null=True)),
                ('furnished', models.BooleanField(blank=True, help_text='A furnished apartment is required.', null=True)),
                ('additional_facilities', models.CharField(blank=True, help_text='Any additional facilities the tenant requires.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(help_text='The tenant who owns this preference.', limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='recommendat_tenant__12263b_idx'), models.Index(fields=['location'], name='recommendat_locatio_b44a6a_idx'), models.Index(fields=['max_rent'], name='recommendat_max_ren_b92779_idx'), models.Index(fields=['apartment_type'], name='recommendat_apartme_887071_idx')],
            },
        ),
    ]
