# Generated by Django 6.1 on 2026-08-30 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_apartmentimage'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('weighted_knn', 'Weighted KNN')], default='weighted_knn', max_length=20)),
                ('k', models.PositiveIntegerField(default=5, help_text='Number of nearest neighbours used for this run.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preference', models.ForeignKey(blank=True, help_text='The preference that generated this recommendation run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='recommendations.preference')),
                ('tenant', models.ForeignKey(help_text='The tenant who owns this recommendation run.', limit_choices_to={'role': 'TENANT'}, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecommendationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(help_text='1-based ranking position (lowest distance = rank 1).')),
                ('distance', models.FloatField(help_text='Weighted Euclidean distance from the tenant query vector.')),
                ('similarity', models.FloatField(help_text='Bounded preference-match score derived from the distance.')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_items', to='apartments.apartment')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.recommendation')),
            ],
            options={
                'ordering': ['recommendation', 'rank'],
            },
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['tenant'], name='recommendat_tenant__c9fae9_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['preference'], name='recommendat_prefere_c27f3b_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendationitem',
            index=models.Index(fields=['recommendation', 'rank'], name='recommendat_recomme_109b4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendationitem',
            constraint=models.UniqueConstraint(fields=('recommendation', 'apartment'), name='unique_recommendation_apartment'),
        ),
    ]
