# Generated by Django 6.1 on 2026-08-31 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AUTH', 'Authentication'), ('ADMIN', 'Administrative Action'), ('DATA', 'Data Integrity'), ('SYSTEM', 'System Event')], help_text='High-level event category.', max_length=20)),
                ('action', models.CharField(help_text='Human-readable description of the event.', max_length=255)),
                ('target_content_type', models.CharField(blank=True, help_text="Django content type of the target object (e.g. 'accounts.User').", max_length=100)),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, help_text='Primary key of the target object, if any.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address at the time of the event.', null=True)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON payload for additional context.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='The user who performed this action (may be NULL for system events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='audit_audit_categor_b9a693_idx'), models.Index(fields=['user'], name='audit_audit_user_id_c5b9b3_idx'), models.Index(fields=['created_at'], name='audit_audit_created_7710b7_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='audit_audit_target__5c3007_idx')],
            },
        ),
    ]
